modLoader = "javafml"
loaderVersion = "[42,)"
license = "MIT"

[[mods]]
modId = "i18nupdatemod"
version = "${version}"
displayName = "I18nUpdateMod Non-LTS Architectury"
credits= "TartaricAcid, baka-gourd, exzhawk"
authors = "TexTrue, TexTrueStudio"
description = '''
自动汉化更新
'''
logoFile = "icon.png"

[[dependencies.i18nupdatemod]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"