modLoader = "javafml"
loaderVersion = "[30,)"
license = "MIT"

[[mods]]
modId = "i18nupdatemod"
version = "${version}"
displayName = "I18nUpdateMod Non-LTS"
logoFile="icon.png"
credits="TartaricAcid, baka-gourd, exzhawk"
authors="TexTrue, TexTrueStudio"
description='''
自动汉化更新模组
'''

[[dependencies.i18nupdatemod]]
modId = "forge"
mandatory = true
versionRange = "[30,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15,)"
ordering = "NONE"
side = "BOTH"